on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '40 * * * *'

name: Readme

jobs:
  update_readme:
    name: Update readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run action
        uses: pypi-data/toolchain/actions/update-readme@main
        with:
          workspace: ${{ github.workspace }}
