on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Limit'
        required: true

name: Trigger

jobs:
  trigger:
    name: Trigger workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Run action
        uses: pypi-data/toolchain/actions/trigger@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workspace: ${{ github.workspace }}
          run-id: ${{ github.run_number }}
          limit: ${{ inputs.limit }}

  update_readme:
    name: Update readme
    runs-on: ubuntu-latest
    needs: [ trigger ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Run action
        uses: pypi-data/toolchain/actions/update-readme@main
        with:
          workspace: ${{ github.workspace }}

  update_index:
    name: Update Index
    runs-on: ubuntu-latest
    needs: [ trigger ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Run action
        uses: pypi-data/toolchain/actions/update-index@main
        with:
          workspace: ${{ github.workspace }}
          token: ${{ secrets.GITHUB_TOKEN }}
