on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Limit'
        required: false

name: Trigger

jobs:
  trigger:
    name: Test workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run action
        uses: pypi-data/toolchain/actions/get-code@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workspace: ${{ github.workspace }}
          run-id: ${{ github.run_number }}
          limit: ${{ inputs.limit }}

  update_readme:
    name: Update readme
    runs-on: ubuntu-latest
    needs: [ trigger ]
    steps:
      - uses: actions/checkout@v3
      - name: Run action
        uses: pypi-data/toolchain/actions/update-readme@main
        with:
          workspace: ${{ github.workspace }}
